version: "3.7"
services:
  janus:
    build: ./janus
    environment:
      MEDIA_RTP_PORT_RANGE: $MEDIA_RTP_PORT_RANGE
      ADMIN_SECRET: $ADMIN_SECRET
    volumes:
      - ./janus/config:/config
      - ./data/janus:/data
    ports:
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "$MEDIA_RTP_PORT_RANGE:$MEDIA_RTP_PORT_RANGE"
    command: /config/start.sh
